package Good_Code.Beverage_Without_Hook;

import Good_Code.Beverage_Without_Hook.Concrete_Beverages.*;

public class BeverageTemplateDemo {
    public static void main(String[] args) {
        Beverage coffee = new CoffeeBeverage();
        Beverage tea = new TeaBeverage();
        System.out.println("Making coffee...");
        coffee.prepareRecipe();
        System.out.println("nMaking tea...");
        tea.prepareRecipe();
    }
}

/*

Output :
Making coffee...
Boiling water...
Brewing coffee...
Pouring into cup...
Adding sugar and milk...
nMaking tea...
Boiling water...
Steeping tea bag...
Pouring into cup...
Adding lemon...

*/