package Ugly_Code;

import Ugly_Code.Concrete_Beverages.*;

public class TraditionalBeverageDemo {
    public static void main(String[] args) {
        Coffee coffee = new Coffee();
        Tea tea = new Tea();
        System.out.println("Making coffee...");
        coffee.prepare();
        System.out.println("nMaking tea...");
        tea.prepare();
    }
}

/*

Output :
Making coffee...
Boiling water...
Brewing coffee...
Pouring into cup...
Adding sugar and milk...
nMaking tea...
Boiling water...
Steeping tea bag...
Pouring into cup...
Adding lemon...

*/
